package com.example.urlshortener.service;

import com.example.urlshortener.common.ShorteningUtil;
import com.example.urlshortener.dto.LongUrlRequest;
import com.example.urlshortener.dto.ShortUrlRequest;
import com.example.urlshortener.model.UrlEntity;
import com.example.urlshortener.repository.ShortenerRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class UrlService {

    Logger logger = LoggerFactory.getLogger(UrlService.class);

    private final ShortenerRepository shortenerRepository;

    @Autowired
    public UrlService(ShortenerRepository shortenerRepository) {
        this.shortenerRepository = shortenerRepository;
    }

    private UrlEntity get(Long id) {
        logger.info(String.format("Fetching Url from database for Id %d", id));
        UrlEntity urlEntity = shortenerRepository.findById(id).get();
        return urlEntity;
    }

    /**
     * Uses the Base62 encoded to convert to Base10 number and fetches the corresponding record from the database
     *
     * @param shortenString Base62 encoded string
     * @return FullUrl object
     */
    public LongUrlRequest getFullUrl(String shortenString) {
        logger.debug("Converting Base 62 string %s to Base 10 id");
        Long id = ShorteningUtil.strToId(shortenString);
        logger.info(String.format("Converted Base 62 string %s to Base 10 id %s", shortenString, id));

        logger.info(String.format("Retrieving full url for %d", id));
        return new LongUrlRequest(this.get(id).getFullUrl());
    }

    private UrlEntity save(LongUrlRequest longUrlRequest) {
        return shortenerRepository.save(new UrlEntity(longUrlRequest.getFullUrl()));
    }

    /**
     * It saves the full url to database and uses the autogenerated id to convert to Base62 string
     *
     * @param longUrlRequest FullUrl object to be converted to shortened url
     * @return ShortUrl object
     */
    public ShortUrlRequest getShortUrl(LongUrlRequest longUrlRequest) {

        logger.info("Checking if the url already exists");
        List<UrlEntity> savedUrls = null;
        savedUrls = checkFullUrlAlreadyExists(longUrlRequest);

        UrlEntity savedUrl = null;

        if (savedUrls.isEmpty()) {
            logger.info(String.format("Saving Url %s to database", longUrlRequest.getFullUrl()));
            savedUrl = this.save(longUrlRequest);
            logger.debug(savedUrl.toString());
        }
        else {
            savedUrl = savedUrls.get(0);
            logger.info(String.format("url: %s already exists in the database. skipped insert", savedUrl));
        }

        logger.debug(String.format("Converting Base 10 %d to Base 62 string", savedUrl.getId()));
        String shortUrlText = ShorteningUtil.idToStr(savedUrl.getId());
        logger.info(String.format("Converted Base 10 %d to Base 62 string %s", savedUrl.getId(), shortUrlText));

        return new ShortUrlRequest(shortUrlText);
    }

    /**
     * Check if Url already exists in the database to prevent having same url stored multiple times
     *
     * @param longUrlRequest
     * @return list of UrlEntity objects, list will be empty if no results found
     */
    private List<UrlEntity> checkFullUrlAlreadyExists(LongUrlRequest longUrlRequest) {
        return shortenerRepository.findUrlByFullUrl(longUrlRequest.getFullUrl());
    }
}
